version: '3.8'

services:
  postgres:
    image: postgres:13.7
    container_name: fuse-stock-trading-db
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-fuse_stock_trading_dev}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-fuse_stock_trading_dev}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fuse-network

  db-migrate:
    image: amacneil/dbmate:latest
    container_name: fuse-db-migrate
    environment:
      DATABASE_URL: postgres://${DB_USERNAME:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-fuse_stock_trading_dev}?sslmode=disable
    volumes:
      - ./db/migrations:/db/migrations
      - ./dbmate.yml:/dbmate.yml
    depends_on:
      postgres:
        condition: service_healthy
    command: up
    networks:
      - fuse-network



volumes:
  postgres_data:

networks:
  fuse-network:
    driver: bridge
