service: fuse-stock-trading-service

frameworkVersion: '4'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          path: /
          method: get
