service: fuse-stock-trading-service

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild: ${file(./esbuild.config.js)}
  # Dotenv plugin configuration
  dotenv:
    path: ./.env
    include:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - DB_PORT
      - VENDOR_API_URL
      - VENDOR_API_KEY
      - NODE_ENV
    logging: true
  # RDS database configuration
  rds:
    dbName: ${self:provider.environment.DB_NAME}
    dbUsername: ${self:provider.environment.DB_USERNAME}
    dbPassword: ${self:provider.environment.DB_PASSWORD}
    dbInstanceClass: db.t3.micro
    allocatedStorage: 20
    engineVersion: '13.7'
    port: ${self:provider.environment.DB_PORT}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${env:NODE_ENV, self:provider.stage}
    # Database environment variables
    DB_USERNAME: ${env:DB_USERNAME, 'postgres'}
    DB_PASSWORD: ${env:DB_PASSWORD, 'postgres'}
    DB_NAME: ${env:DB_NAME, 'fuse_stock_trading_${self:provider.stage}'}
    DB_HOST: ${env:DB_HOST, 'localhost'}
    DB_PORT: ${env:DB_PORT, '5432'}
    # Vendor API environment variables
    VENDOR_API_URL: ${env:VENDOR_API_URL, 'https://api.challenge.fusefinance.com'}
    VENDOR_API_KEY: ${env:VENDOR_API_KEY, 'nSbPbFJfe95BFZufiDwF32UhqZLEVQ5K4wdtJI2e'}
  # IAM permissions to access RDS
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds:*
      Resource: '*'

functions:
  listStocks:
    handler: src/handlers/stocks/list.handler
    events:
      - http:
          path: /stocks
          method: get
          cors: true
           
  getUserPortfolios:
    handler: src/handlers/portfolios/list.handler
    events:
      - http:
          path: /users/{userId}/portfolios
          method: get
          cors: true
          request:
            parameters:
              paths:
                userId: true
                
  buyStock:
    handler: src/handlers/portfolios/buy-stock.handler
    timeout: 15
    events:
      - http:
          path: /stocks/{symbol}/buy
          method: post
          cors: true
          request:
            parameters:
              paths:
                symbol: true

# AWS CloudFormation resources definition
resources: ${file(./resources/rds.yml)}
