Resources:
  StockTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stockTokensTable}
      AttributeDefinitions:
        - AttributeName: symbol
          AttributeType: S
      KeySchema:
        - AttributeName: symbol
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  StockCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stockCacheTable}
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true 